Category.create(name: 'Food/Eating')
Category.create(name: 'Exercise')
Category.create(name: 'Family Outing')
Category.create(name: 'Game')


Team.create(family_name: 'Johnson')
User.create(username: 'BobRox', team_id: 1, age: 54)
User.create(username: 'MommaBear', team_id: 1, age: 52)
User.create(username: 'suzanne', team_id: 1, age: 14)
User.create(username: 'roxanne', team_id: 1, age: 12)

Team.create(family_name: 'Smith')
User.create(username: 'PappaBear', team_id: 2, age: 54)
User.create(username: 'MotherlyLove', team_id: 2, age: 30)
User.create(username: 'littlejimmy', team_id: 2, age: 54)
User.create(username: 'littletimmy', team_id: 2, age: 54)

Team.create(family_name: 'Jones')
User.create(username: 'Dad', team_id: 3, age: 54)
User.create(username: 'Mom', team_id: 3, age: 48)
User.create(username: 'number1', team_id: 3, age: 20)
User.create(username: 'boy1', team_id: 3, age: 15)
User.create(username: 'boy2', team_id: 3, age: 14)

Team.create(family_name: 'Williams')
User.create(username: 'MisterDad', team_id: 4, age: 54)
User.create(username: 'MissMom', team_id: 4, age: 54)
User.create(username: 'twin1', team_id: 4, age: 18)
User.create(username: 'twin2', team_id: 4, age: 18)
User.create(username: 'boywonder', team_id: 4, age: 6)
User.create(username: 'troublemaker', team_id: 4, age: 5)


Task.create(point_value: 3, description: 'Play a game of basketball')
Task.create(point_value: 3, description: 'Play a game of pepper (volleyball)')
Task.create(point_value: 4, description: 'Family bike ride')
Task.create(point_value: 5, description: 'Cook dinner together')
Task.create(point_value: 5, description: 'Eat a meal at the table together. NO electronic devices')
Task.create(point_value: 3, description: 'Take a walk around the block together')
Task.create(point_value: 4, description: 'Volunteer together')
Task.create(point_value: 3, description: 'Go ice skating or roller blading')
Task.create(point_value: 2, description: 'Go bowling')
Task.create(point_value: 2, description: 'Plan a camping trip')
Task.create(point_value: 4, description: 'Camp out in the backyard')
Task.create(point_value: 2, description: 'Make s’mores')
Task.create(point_value: 3, description: 'Build something with Legos/Lincoln Logs/K’nex')
Task.create(point_value: 2, description: 'Arts and Crafts')
Task.create(point_value: 2, description: 'Learn a create card game')
Task.create(point_value: 1, description: 'Do a word search puzzle')
Task.create(point_value: 3, description: 'Laughter Yoga')
Task.create(point_value: 2, description: 'Do a puzzle')
Task.create(point_value: 3, description: 'Jump rope')
Task.create(point_value: 3, description: 'Go out for ice cream')
Task.create(point_value: 3, description: 'Go to your local farmers market')
